import type { Metadata } from 'next'
import '../styles/globals.css'
import { Providers } from '@/components/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div className="mx-auto w-8/12">{children}</div>
}
